# Generated by Django 5.0.6 on 2024-08-12 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_applied', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'bill_detail',
                'verbose_name_plural': 'bill_details',
                'db_table': 'customer_bill_detail',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'db_table': 'users_customer',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('special_instructions', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'delivery_detail',
                'verbose_name_plural': 'delivery_details',
                'db_table': 'customer_delivery_detail',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OfferCupen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('offer_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_description', models.TextField()),
                ('is_percentage', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'offer_cupen',
                'verbose_name_plural': 'offer_cupens',
                'db_table': 'customer_offer_cupen',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amouunt', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.fooditem')),
                ('restorant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.restorant')),
            ],
            options={
                'verbose_name': 'cart',
                'verbose_name_plural': 'carts',
                'db_table': 'customer_cart',
                'ordering': ['-id'],
            },
        ),
    ]
