# Generated by Django 5.0.6 on 2024-07-29 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_applied', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'verbose_name': 'bill_detail',
                'verbose_name_plural': 'bill_details',
                'db_table': 'customer_bill_detail',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'verbose_name': 'delivery_detail',
                'verbose_name_plural': 'delivery_details',
                'db_table': 'customer_delivery_detail',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OfferCupen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_code', models.CharField(max_length=50)),
                ('offer_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_description', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'verbose_name': 'offer_cupen',
                'verbose_name_plural': 'offer_cupens',
                'db_table': 'customer_offer_cupen',
                'ordering': ['-id'],
            },
        ),
    ]
