# Generated by Django 5.0.6 on 2024-08-05 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_billdetails_deliverydetails_offercupen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offercupen',
            name='customer',
        ),
    ]
