# Generated by Django 5.0.6 on 2024-08-19 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_offercupen_start_time_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdetails',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.address'),
        ),
    ]
