# Generated by Django 5.0.6 on 2024-08-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CREDIT/DEBIT/UPI', 'Credit/Debit/UPI'), ('COD', 'Cash on Delivery')], default='COD', max_length=20),
        ),
    ]
