# Generated by Django 5.0.6 on 2024-08-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_orderitem_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_status',
            field=models.CharField(choices=[('Preparing', 'Preparing'), ('Ready for Pickup/Delivery', 'Ready for Pickup/Delivery'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Preparing', max_length=50),
        ),
    ]
