# Generated by Django 5.0.6 on 2024-08-21 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_orderitem_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Preparing', 'Preparing'), ('Ready for Pickup/Delivery', 'Ready for Pickup/Delivery'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Preparing', max_length=50),
        ),
    ]
