# Generated by Django 5.0.6 on 2024-08-21 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_remove_orderitem_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_status',
        ),
    ]
