# Generated by Django 5.0.6 on 2024-08-12 06:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foodcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'foodcategory',
                'verbose_name_plural': 'foodcategories',
                'db_table': 'web_foodcategory',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Restorant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('discription', models.CharField(max_length=255)),
                ('rating', models.FloatField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('discount', models.IntegerField(help_text='Enter a discount value between 0 and 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('image', models.ImageField(upload_to='restorants')),
            ],
            options={
                'verbose_name': 'restorant',
                'verbose_name_plural': 'restorants',
                'db_table': 'web_restorant',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RestorantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='restorant_categorys')),
            ],
            options={
                'verbose_name': 'restorant_category',
                'verbose_name_plural': 'restorant_categorys',
                'db_table': 'web_restorant_category',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Fooditem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='fooditems')),
                ('price', models.FloatField()),
                ('is_veg', models.BooleanField(default=False)),
                ('foodcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.foodcategory')),
                ('restorant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.restorant')),
            ],
            options={
                'verbose_name': 'fooditem',
                'verbose_name_plural': 'fooditems',
                'db_table': 'web_fooditem',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='restorant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.restorant'),
        ),
        migrations.AddField(
            model_name='restorant',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.restorantcategory'),
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slides')),
                ('restorant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.restorant')),
            ],
            options={
                'verbose_name': 'slide',
                'verbose_name_plural': 'slides',
                'db_table': 'web_slide',
                'ordering': ['-id'],
            },
        ),
    ]
