# Generated by Django 5.0.6 on 2024-07-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='vegornon',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='is_veg',
            field=models.BooleanField(default=False),
        ),
    ]
