# Generated by Django 5.0.6 on 2024-07-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_fooditem_vegornon_fooditem_is_veg'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
